### ISSUE TITLE
8.0 stock_quant_merge Crash when unreserve move linked to quants on multiple locations

### ISSUE THREAD

**Issue by alexis-via** [OCA/stock-logistics-warehouse#109]
Here is the scenario to reproduce the bug on Odoo v8 with an update OCA/stock-logistics-warehouse/8.0 branch:

1) In a demo database, install the module stock_quant_merge
2) Create a new stockable product TEST1
3) Let's say that we have 5 units of TEST1 on Self1 and 2 units on Shelf 2.
In the "Inventory" Tab, click on the "Update" button next to "Quantity on Hand":
- Location : WH/Stock/Self 1
- New Quantity on hand : 5
  Click a second time on the Update button:
- Location : WH/Stock/Self 2
- New Quantity on hand : 2
  5) Create a new sale order with one sale order line with:
- product: TEST1
- quantity: 6
  Confirm the sale order.
  6) On the related outgoing picking, click on "Check Availability": 6 units should be reserved in stock and the picking should become "Ready to transfer"
  7) Go back to the sale order and click on the "Cancel Order" button (which will unreserve the stock)
  You get an error message : Expected singleton: stock.quant(41, 42)

Here is the backtrace:

```
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo8/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo8/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/alexis/new_boite/dev/odoo8/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/sale/sale.py", line 599, in action_cancel
    sale_order_line_obj.button_cancel(cr, uid, line_ids, context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/sale_stock/sale_stock.py", line 364, in button_cancel
    return super(sale_order_line, self).button_cancel(cr, uid, ids, context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/sale/sale.py", line 1047, in button_cancel
    procurement_obj.cancel(cr, uid, sum([l.procurement_ids.ids for l in lines], []), context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/stock/procurement.py", line 103, in cancel
    self.propagate_cancel(cr, uid, procurement, context=ctx)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/purchase/purchase.py", line 1299, in propagate_cancel
    return super(procurement_order, self).propagate_cancel(cr, uid, procurement, context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/stock/procurement.py", line 93, in propagate_cancel
    self.pool.get('stock.move').action_cancel(cr, uid, [m.id for m in procurement.move_ids], context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/addons/stock/stock.py", line 2336, in action_cancel
    self.pool.get("stock.quant").quants_unreserve(cr, uid, move, context=context)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 360, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/alexis/new_boite/dev/stock-logistics-warehouse8/stock_quant_merge/models/stock.py", line 52, in quants_unreserve
    quants.merge_stock_quants()
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/stock-logistics-warehouse8/stock_quant_merge/models/stock.py", line 33, in merge_stock_quants
    quants = self.search(self._mergeable_domain())
  File "/home/alexis/new_boite/dev/odoo8/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/stock-logistics-warehouse8/stock_quant_merge/models/stock.py", line 17, in _mergeable_domain
    self.ensure_one()
  File "/home/alexis/new_boite/dev/odoo8/openerp/models.py", line 5307, in ensure_one
    raise except_orm("ValueError", "Expected singleton: %s" % self)
except_orm: ('ValueError', 'Expected singleton: stock.quant(41, 42)')
```

Code analysis: the bug is quite easy to understand:

In the method quants_unreserve(), you have:

```
quants = move.reserved_quant_ids
```

In our scenario, the move will reserve 2 quants : one on Shelf1 and one on Self2, so quants is a recordset with 2 records.

Then we do:

```
quants.merge_stock_quants()
```

So, in the method merge_stock_quants(), self will have 2 records

Then we do:

```
self._mergeable_domain()
```

But, at the beginning of the method _mergeable_domain(), we have:

```
self.ensure_one()
```

So it blocks !

**Comment by clonedagain** [comment]
@pedrobaeza @oihane @lbellier @rvalyi for your information.

I think this is a mistake in my change in b1c856855bca0208e90268d122870fd60f6ff166
A quick fix is probably to revert it.

I'm off for the day, can someone suggest a durable fix that would keep the modularity please?

**Comment by clonedagain** [comment]
@alexis-via can you propose an automatic test please?

**Comment by rvalyi** [comment]
gahhh sorry I didn't spot the regression

**Comment by alexis-via** [comment]
I am not familiar with this code, but when you read Lionel's commit https://github.com/OCA/stock-logistics-warehouse/commit/b1c856855bca0208e90268d122870fd60f6ff166 it's obvious that

```
quants = self.search(self._mergeable_domain())
```

should be:

```
quants = self.search(quant2merge._mergeable_domain())
```

**Comment by rvalyi** [comment]
@alexis-via you are right!

**Comment by pedrobaeza** [comment]
Fixed directly!
