### ISSUE TITLE
Settings showing an error

### ISSUE THREAD

**Issue by bengush** [OCA/stock-logistics-warehouse#1131]
![Capture](https://user-images.githubusercontent.com/46672484/115053568-caee5280-9ece-11eb-8a56-f3b84f66072a.PNG)
Error:

Traceback:
TypeError: field_utils.format[(formatType || this.formatType)] is not a function
    at Class._formatValue (http://:8069/web/content/50027-8e0e774/web.assets_backend.js:900:1237)
    at Class._render (http://:8069/web/content/50027-8e0e774/web.assets_backend.js:894:167)
    at Class._render (http://:8069/web/content/50027-8e0e774/web.assets_backend.js:1160:1163)
    at Class.prototype.<computed> [as _render] (http://web/content/49807-6966dbe/web.assets_common.js:4622:488)
    at http://:8069/web/content/50027-8e0e774/web.assets_backend.js:898:1417

**Comment by pedrobaeza** [comment]
And is due to any module in this repository?

**Comment by bengush** [comment]
There is no error showing in the logs

**Comment by bengush** [comment]
> And is due to any module in this repository?

I was installing a module MRP and this error came up, though there is no error showing in the logs

**Comment by pedrobaeza** [comment]
Sorry, but if you can't reproduce the problem in OCA runbot, then it's not something of the module, but your deployment or your process, so nothing can be done here.
