### ISSUE TITLE
Error Picking Type Stock Request (stock_request_picking_type) V.14

### ISSUE THREAD

**Issue by ToonBS** [OCA/stock-logistics-warehouse#1426]
After Click Operation Type Stock Requests.

![image](https://user-images.githubusercontent.com/79127650/170943605-f47fd3d6-f646-4843-a1c5-3845e615ec1a.png)

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/root/odoo-14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/root/odoo-14.0/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/root/odoo-14.0/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/root/odoo-14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/root/odoo-14.0/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/root/odoo-14.0/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/root/odoo-14.0/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/root/odoo-14.0/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/root/odoo-14.0/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/root/odoo-14.0/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/root/odoo-14.0/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/root/odoo-14.0/odoo/addons/stock_request_picking_type/models/stock_picking_type.py", line 46, in get_stock_request_order_picking_type_action
    return self._get_action("stock_request_picking_type.action_picking_dashboard")
  File "/root/odoo-14.0/odoo/addons/stock/models/stock_picking.py", line 219, in _get_action
    action_context = literal_eval(action['context'])
  File "/usr/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.6/ast.py", line 66, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.6/ast.py", line 65, in <genexpr>
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/odoo-14.0/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/root/odoo-14.0/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: malformed node or string: <_ast.Name object at 0x7f816fff9f60>

![image](https://user-images.githubusercontent.com/79127650/170943951-18bf8530-0e26-43f6-99af-1edc968b58ff.png)

**Comment by bunhin** [comment]
I confirm that i have the same problem
