### ISSUE TITLE
stock_inventory_hierarchical_location cause import error when starting server

### ISSUE THREAD

**Issue by andhit-r** [OCA/stock-logistics-warehouse#152]
Hi,

I notice that **stock_inventory_hierarchical_location** module cause import error when starting server. The problems are in **inventory_hierarchical_location.py** line **24** and **27**. Bellow are the messages:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/openerp/http.py", line 1289, in **call**
    self.load_addons()
  File "/opt/odoo/odoo/openerp/http.py", line 1308, in load_addons
    m = **import**('openerp.addons.' + module)
  File "/opt/odoo/odoo/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/oca_stock_logistics_warehouse/stock_inventory_hierarchical_location/**init**.py", line 21, in <module>
    from . import inventory_hierarchical_location
  File "/opt/odoo/oca_stock_logistics_warehouse/stock_inventory_hierarchical_location/inventory_hierarchical_location.py", line 27, in <module>
    from openerp.addons.stock_inventory_hierarchical.hierarchial_inventory import PARENT_VALUES
ImportError: No module named hierarchial_inventory

Could someone confirm this?

**Comment by andhit-r** [comment]
PR for this issue https://github.com/OCA/stock-logistics-warehouse/pull/154
