### ISSUE TITLE
[stock_inventory_hierarchical][8.0][Bug] _complete_name() takes at least 6 arguments (5 given)

### ISSUE THREAD

**Issue by andhit-r** [OCA/stock-logistics-warehouse#160]
module: stock_inventory_hierarchical
version: 8.0
Repo SHA: c869321ee266db13a6f2d56c7bd71a08cc593b9b

**Steps to reproduce**
1. Install stock_inventory_hierarchical
2. Create new inventory valuation

**Current behavior**
Exception raised:
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/opt/odoo/odoo/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 5147, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/opt/odoo/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3141, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 3187, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/opt/odoo/odoo/openerp/models.py", line 5574, in **getitem**
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/openerp/fields.py", line 817, in **get**
    self.determine_value(record)
  File "/opt/odoo/odoo/openerp/fields.py", line 919, in determine_value
    self.compute_value(recs)
  File "/opt/odoo/odoo/openerp/fields.py", line 875, in compute_value
    self._compute_value(records)
  File "/opt/odoo/odoo/openerp/fields.py", line 867, in _compute_value
    self.compute(records)
  File "/opt/odoo/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
TypeError: _complete_name() takes at least 6 arguments (5 given)

**Expected behavior**

No exception

**Note**
I could not reproduce it on runbot

**Comment by andhit-r** [comment]
Solve. Solution: Update odoo to latest commit
