### ISSUE TITLE
[14.0] web_ir_actions_act_view_reload: action seems to be broken

### ISSUE THREAD

**Issue by TheMule71** [OCA/stock-logistics-warehouse#1632]
## Module
web_ir_actions_act_view_reload

## Describe the bug
When trying using the module as documented, I get `KeyError: 'ir.actions.act_view_reload'`. My code is
in the model:
```
def reload(self):
    self.ensure_one()
    return {"type": "ir.actions.act_view_reload"}
```
in the view:
```
<button type="object" name="reload" string="Refresh" class="oe_inline" icon="fa-refresh"/>
```
Please read 'Additional context' below.

## To Reproduce
**Affected versions**:
tested only on 14.0

1. Install the module and follow instructions to use it.

**Expected behavior**
The action should be defined.

**Additional context**
Other modules seem to be affected as well (in runboat), so most likely it's not my code or my environment.

E.g. the Refresh button in `stock_measuring_device` has the same problem, tested in runboat.

`http://oca-stock-logistics-warehouse-14-0-4e338d152d79.runboat.odoo-community.org/web#id=1&active_id=1&model=measuring.wizard&view_type=form&cids=&menu_id=183`

```Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1394, in call_button
    return clean_action(action, env=request.env)
  File "/opt/odoo/addons/web/controllers/main.py", line 332, in clean_action
    readable_fields = env[action['type']]._get_readable_fields()
  File "/opt/odoo/odoo/api.py", line 476, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'ir.actions.act_view_reload'```

**Comment by Aceeper2** [comment]
good!

**Comment by rousseldenis** [comment]
@yajo
