### ISSUE TITLE
stock_move_location Client Error

### ISSUE THREAD

**Issue by grekollc** [OCA/stock-logistics-warehouse#1679]
## Module
stock_move_location

## Describe the bug
UncaughtPromiseError > OwlError
Uncaught Promise > Invalid props for component 'ActionMenus': 'items' has not the correct shape (unknown key '0')

OwlError: Invalid props for component 'ActionMenus': 'items' has not the correct shape (unknown key '0')
    at Object.validateProps (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:1683:67)
    at InventoryReportListController.slot2 (eval at compile (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:2040:370), <anonymous>:35:15)
    at callSlot (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:1652:25)
    at ControlPanel.template (eval at compile (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:2040:370), <anonymous>:72:15)
    at ControlPanel.template (eval at compile (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:2040:370), <anonymous>:18:27)
    at Fiber._render (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:1477:96)
    at Fiber.render (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:1476:6)
    at ComponentNode.updateAndRender (https://greko.odoo.com/web/assets/33907-746b4a3/web.assets_common.min.js:1572:49)

## To Reproduce
current V16

Inventory > reporting > location > select check box on any line item

**Expected behavior**
Select the line item without a client error

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by rousseldenis** [comment]
@grekollc Thanks for this report.

Could you add some context information as I couldn't reproduce it on runboat 16?

**Comment by grekollc** [comment]
Here is a video showing the error.
Also shown in the video is a problem with the module not populating the
locations correctly.
https://watch.screencastify.com/v/MkaMg2jAJ3jNSDWrIM0A
<https://mailtrack.io/trace/link/05a390abe03604f469b90f1cdfa9aaa6b80a3434?url=https%3A%2F%2Fwatch.screencastify.com%2Fv%2FMkaMg2jAJ3jNSDWrIM0A&userId=8349039&signature=4c9b595e898e2b07>

**Comment by rousseldenis** [comment]
@grekollc Ok, it occurs on Enterprise version only.

@tupaq As you migrated this one.

**Comment by grekollc** [comment]
Is this able to work on enterprise?
