### ISSUE TITLE
UnicodeEncodeError: 'ascii' 

### ISSUE THREAD

**Issue by dhecar** [OCA/stock-logistics-warehouse#179]
Hello, i'm trying to use the module stock_reserve_sale , but in products with spanish charactes like  ñ o with ü ï  etc characters im'm geting this error.

Client Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/http.py", line 204, in dispatch
    response["result"] = method(self, *_self.params)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1137, in call_button
    action = self._call_kw(req, model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1125, in _call_kw
    return getattr(req.session.model(model), method)(_args, **kwargs)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 42, in proxy
    result = self.proxy.execute_kw(self.session._db, self.session._uid, self.session._password, self.model, method, args, kw)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 30, in proxy_method
    result = self.session.send(self.service_name, method, *args)
  File "/opt/odoo/odoo-server/addons/web/session.py", line 103, in send
    raise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)

Server Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/odoo/odoo-server/openerp/netsvc.py", line 306, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/odoo/odoo-server/openerp/service/web_services.py", line 632, in dispatch
    res = fn(db, uid, _params)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 193, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 133, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 202, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/odoo/odoo-server/openerp/osv/osv.py", line 190, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/odoo/custom/addons/extras/stock-logistics-warehouse/stock_reserve_sale/wizard/sale_stock_reserve.py", line 109, in button_reserve
    self.stock_reserve(cr, uid, ids, line_ids, context=context)
  File "/opt/odoo/custom/addons/extras/stock-logistics-warehouse/stock_reserve_sale/wizard/sale_stock_reserve.py", line 86, in stock_reserve
    context=context)
  File "/opt/odoo/custom/addons/extras/stock-logistics-warehouse/stock_reserve_sale/wizard/sale_stock_reserve.py", line 65, in _prepare_stock_reservation
    'name': "{} ({})".format(line.order_id.name, line.name),
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-42: ordinal not in range(128)

**Comment by pedrobaeza** [comment]
The solution would be to prefix the string format with `u`: `...'name': u"{} ({})".format(line.order_id.name, line.name),`

Fixed in https://github.com/OCA/stock-logistics-warehouse/commit/17d447030011980d1bd21674745e06b5a3da4a59 and https://github.com/OCA/stock-logistics-warehouse/commit/3aa51b052aff7c15fd9492fd05dbb77bfa76e26f
