### ISSUE TITLE
Missing field string information for the field 'mts_rule_id' from the 'stock.rule' model"

### ISSUE THREAD

**Issue by dooob6** [OCA/stock-logistics-warehouse#1863]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by dooob6** [comment]
I installed the module in the online platform by adding the zip archive and this error occured.

**Comment by dooob6** [comment]
OwlError: The following error occurred in onWillStart: "Missing field string information for the field 'mts_rule_id' from the 'stock.rule' model"
    at wrapError (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:16292:23) (/web/static/lib/owl/owl.js:2604)
    at onWillStart (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:16335:29) (/web/static/lib/owl/owl.js:2647)
    at View.setup (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:64913:9) (/web/static/src/views/view.js:194)
    at new ComponentNode (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:16044:28) (/web/static/lib/owl/owl.js:2356)
    at https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:19466:28 (/web/static/lib/owl/owl.js:5778)
    at ControllerComponent.template (eval at compile (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:19237:20), <anonymous>:11:27) (/web/static/lib/owl/owl.js:5549)
    at Fiber._render (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:15410:38) (/web/static/lib/owl/owl.js:1722)
    at Fiber.render (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:15402:18) (/web/static/lib/owl/owl.js:1714)
    at ComponentNode.initiateRender (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_common.js:16066:23) (/web/static/lib/owl/owl.js:2378)

Caused by: Error: Missing field string information for the field 'mts_rule_id' from the 'stock.rule' model
    at https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78075:27 (/web/static/src/legacy/legacy_load_views.js:69)
    at traverse (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78013:9) (/web/static/src/legacy/legacy_load_views.js:7)
    at https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78015:13 (/web/static/src/legacy/legacy_load_views.js:9)
    at Array.forEach (<anonymous>)
    at traverse (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78014:44) (/web/static/src/legacy/legacy_load_views.js:8)
    at processArch (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78065:5) (/web/static/src/legacy/legacy_load_views.js:59)
    at https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78095:78 (/web/static/src/legacy/legacy_load_views.js:89)
    at traverse (https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78013:9) (/web/static/src/legacy/legacy_load_views.js:7)
    at https://baza-de-date-test.odoo.com/web/assets/debug/web.assets_backend.js:78015:13 (/web/static/src/legacy/legacy_load_views.js:9)
    at Array.forEach (<anonymous>)
