### ISSUE TITLE
stock reservation short dump

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#269]
Deal All,
when creating a stock reservation a system error has occurred. Below the log is reported.
Regards
claudio candito

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5484, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5382, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/stock_reserve/model/stock_reserve.py", line 185, in _onchange_product_id
    partner_id=False)
TypeError: onchange_product_id() got an unexpected keyword argument 'prod_id'

**Comment by fanha99** [comment]
hi @ccandito 
could you please give more detail as: which version of odoo are you using, which module are you installed.
regard.

**Comment by ccandito** [comment]
Dear Fanha,
I've implemented a new version 10 and the issue has not been occurred anymore.
thanks
claudio candito
