### ISSUE TITLE
stock_available v10: product creation error/warning on _compute_potential_qty

### ISSUE THREAD

**Issue by BzMB** [OCA/stock-logistics-warehouse#327]
Hi,
During the testing of the module stock_available, we're hitting the following error when we tried to create a new product into the system.

Are we missing any configuration?
Any ideas? 

Thanks in advance.

```
Traceback (most recent call last):
  File "/opt/o10c/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/o10c/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/o10c/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/o10c/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/o10c/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/o10c/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/o10c/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/o10c/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/o10c/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/o10c/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/o10c/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/o10c/odoo/odoo/models.py", line 5506, in onchange
    newval = record[name]
  File "/opt/o10c/odoo/odoo/models.py", line 5214, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/o10c/odoo/odoo/fields.py", line 872, in __get__
    self.determine_draft_value(record)
  File "/opt/o10c/odoo/odoo/fields.py", line 992, in determine_draft_value
    self._compute_value(record)
  File "/opt/o10c/odoo/odoo/fields.py", line 927, in _compute_value
    getattr(records, self.compute)()
  File "/opt/o10c/community/OCA_stock-logistics-warehouse/stock_available/models/product_template.py", line 70, in _compute_potential_qty
    tmpl.potential_qty = res[tmpl.id]['potential_qty']
KeyError: 'potential_qty'
```

**Comment by rousseldenis** [comment]
@BzMB This should be fixed in https://github.com/OCA/stock-logistics-warehouse/pull/305

Bug reported also in https://github.com/OCA/stock-logistics-warehouse/issues/328

**Comment by LoisRForgeFlow** [comment]
Closing as the fix has been made.
