### ISSUE TITLE
system dump in "short demand estimate"

### ISSUE THREAD

**Issue by ccandito** [OCA/stock-logistics-warehouse#368]
Dear All,
I've tried to create "stock demand estimates" and the following dump occurred.
thanks in advance
claudio candito

Traceback (most recent call last):
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 5464, in onchange
    record.mapped(field_seq)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 4966, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 4945, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 5208, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo10/odoo.10-dev/odoo/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/fields.py", line 1012, in determine_value
    record._prefetch_field(self)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 3063, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 3007, in read
    self._read_from_database(stored, inherited)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/models.py", line 3131, in _read_from_database
    cr.execute(query_str, params)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo10/odoo.10-dev/odoo/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "one2many_v_id_59"
LINE 2: ...  WHERE "stock_demand_estimate_sheet_line".id IN ('one2many_...
                                                             ^

**Comment by rousseldenis** [comment]
@ccandito Can you please give us some clues about your environment?

I see a dependency on 'web_widget_x2many_2d_matrix' module.

Is it available on your system ?

I've just tested it on OCA runbot and it's working fine.

**Comment by ccandito** [comment]
Dear Denis,
yes it is.
I've tested it again and reported below the last piece of log before the system dump
thanks in advance
claudio

2018-05-12 07:31:24,473 5432 INFO SANDBOX odoo.sql_db: bad query:  SELECT "stock_demand_estimate_sheet_line"."write_uid" as "write_uid","stock_demand_estimate_sheet_line"."write_date" as "write_date","stock_demand_estimate_sheet_line"."value_x" as "value_x","stock_demand_estimate_sheet_line"."product_id" as "product_id","stock_demand_estimate_sheet_line"."create_date" as "create_date","stock_demand_estimate_sheet_line"."product_uom_qty" as "product_uom_qty","stock_demand_estimate_sheet_line"."create_uid" as "create_uid","stock_demand_estimate_sheet_line"."location_id" as "location_id","stock_demand_estimate_sheet_line"."estimate_id" as "estimate_id","stock_demand_estimate_sheet_line"."id" as "id","stock_demand_estimate_sheet_line"."date_range_id" as "date_range_id","stock_demand_estimate_sheet_line"."value_y" as "value_y" FROM "stock_demand_estimate_sheet_line"
                        WHERE "stock_demand_estimate_sheet_line".id IN ('one2many_v_id_14', 'one2many_v_id_15', 'one2many_v_id_16', 'one2many_v_id_17', 'one2many_v_id_12', 'one2many_v_id_13', 'one2many_v_id_18', 'one2many_v_id_19')  ORDER BY "stock_demand_estimate_sheet_line"."id"  
                    
2018-05-12 07:31:24,473 5432 ERROR SANDBOX odoo.http: Exception during JSON request handling.
Traceback (most recent call last):

**Comment by rousseldenis** [comment]
It seems that this is not linked to module but the manner you installed it
