### ISSUE TITLE
[stock_putaway_product] - exception in MPS

### ISSUE THREAD

**Issue by morphace** [OCA/stock-logistics-warehouse#433]
Odoo 11: if you try to set the min/max values from the MPS with the module installed, you will receive an exception:
```
2018-05-11 14:39:41,390 35896 ERROR odoo11_bct odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/markus/projects/odoo/v11/ce/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/markus/projects/odoo/v11/ce/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/markus/projects/odoo/v11/addons/thirdparty/project_agile/web_syncer/http.py", line 9, in __call__
    result = self.method(*args, **kw)
  File "/Users/markus/projects/odoo/v11/ce/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/markus/projects/odoo/v11/ce/addons/web/controllers/main.py", line 931, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/Users/markus/projects/odoo/v11/ce/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/markus/projects/odoo/v11/ce/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/Users/markus/projects/odoo/v11/ce/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/Users/markus/projects/odoo/v11/ce/odoo/models.py", line 1295, in load_views
    for [v_id, v_type] in views
  File "/Users/markus/projects/odoo/v11/ce/odoo/models.py", line 1295, in <dictcomp>
    for [v_id, v_type] in views
  File "/Users/markus/projects/odoo/ddmrp/OCA/stock-logistics-warehouse/stock_putaway_product/models/product.py", line 42, in fields_view_get
    putaway_field = product_xml.xpath(putaway_path)[0]
IndexError: list index out of range
```

**Comment by rousseldenis** [comment]
@asaunier Can you check this ?

I don't think you can rely on this https://github.com/OCA/stock-logistics-warehouse/blob/ed474f2cc25a76d424f93b77de057dd40d95c69d/stock_putaway_product/models/product.py#L42

You cannot be sure in which order views are loaded I think

**Comment by rousseldenis** [comment]
@morphace What do you mean by MPS ?
In stack trace I don't see product, what form do you modify ?

**Comment by morphace** [comment]
@rousseldenis => the Master Production Schedule - only available in the EE. Should I add a video?

**Comment by morphace** [comment]
@rousseldenis See screenshots => when you click "set target" a form should come up, but you get an exception instead...
![screenshot-localhost-8069-2018 05 11-17-31-17](https://user-images.githubusercontent.com/3398961/39932746-411ecc58-5541-11e8-96bd-2baad4b84263.png)
![screenshot-localhost-8069-2018 05 11-17-31-54](https://user-images.githubusercontent.com/3398961/39932753-43e434fa-5541-11e8-875c-63a103292d68.png)

**Comment by rousseldenis** [comment]
@morphace No, that's ok

@asaunier This is confirmed.

I think in code, you have to ensure on which form you are.

**Comment by asaunier** [comment]
@rousseldenis I have created a PR for this at https://github.com/OCA/stock-logistics-warehouse/pull/434

**Comment by pedrobaeza** [comment]
PR merged, so I close.
