### ISSUE TITLE
Error in stock_resserve test ?

### ISSUE THREAD

**Issue by laetitia-gangloff** [OCA/stock-logistics-warehouse#67]
It seems there is the follwoing error in travis :

There is someone on it ?

2015-08-05 09:23:10,002 22852 DEBUG openerp_test openerp.tools.yaml_import: Exception during evaluation of !python block in yaml_file /home/travis/build/OCA/stock-logistics-warehouse/stock_reserve/test/stock_reserve.yml.
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 581, in process_python
unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
File "/home/travis/build/OCA/stock-logistics-warehouse/stock_reserve/test/stock_reserve.yml", line 96, in <module>
assert orderpoint.procurement_ids[0].state == 'exception', 'procurement must be in exception as there is no rule for procurement'
File "/home/travis/odoo-8.0/openerp/models.py", line 5578, in **getitem**
return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range
2015-08-05 09:23:10,004 22852 ERROR openerp_test openerp.tools.yaml_import: tuple index out of range
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 894, in process
self._process_node(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 907, in _process_node
self.process_python(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 581, in process_python
unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
File "/home/travis/build/OCA/stock-logistics-warehouse/stock_reserve/test/stock_reserve.yml", line 96, in <module>
assert orderpoint.procurement_ids[0].state == 'exception', 'procurement must be in exception as there is no rule for procurement'
File "/home/travis/odoo-8.0/openerp/models.py", line 5578, in __getitem__
return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range
2015-08-05 09:23:10,004 22852 ERROR openerp_test openerp.tests: module stock_reserve: an exception occurred in a test
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 64, in load_test
_load_data(cr, module_name, idref, mode, 'test')
File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 118, in _load_data
tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "/home/travis/odoo-8.0/openerp/tools/convert.py", line 899, in convert_file
convert_yaml_import(cr, module, fp, kind, idref, mode, noupdate, report)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 958, in yaml_import
yaml_interpreter.process(yaml_string)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 894, in process
self._process_node(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 907, in _process_node
self.process_python(node)
File "/home/travis/odoo-8.0/openerp/tools/yaml_import.py", line 581, in process_python
unsafe_eval(code_obj, {'ref': self.get_id}, code_context)
File "/home/travis/build/OCA/stock-logistics-warehouse/stock_reserve/test/stock_reserve.yml", line 96, in <module>
assert orderpoint.procurement_ids[0].state == 'exception', 'procurement must be in exception as there is no rule for procurement'
File "/home/travis/odoo-8.0/openerp/models.py", line 5578, in __getitem__
return self._browse(self.env, (self._ids[key],))
IndexError: tuple index out of range

**Comment by nhomar** [comment]
I don't think so.... be my guest.

**Comment by laetitia-gangloff** [comment]
resolved in https://github.com/OCA/stock-logistics-warehouse/pull/82
