### ISSUE TITLE
stock_request error when using pt_BR

### ISSUE THREAD

**Issue by augustodinizl** [OCA/stock-logistics-warehouse#741]
Good evening

Perhaps is there some misconfig on my instance, but i'm getting that error at using translation
Can somebody help me?

`Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 1005

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(1005,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/web/controllers/main.py", line 1262, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/base/models/ir_actions.py", line 210, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/models.py", line 2797, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/models.py", line 5123, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 985, in __get__
    self.determine_value(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 1098, in determine_value
    self.compute_value(recs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 1052, in compute_value
    self._compute_value(records)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/base/models/ir_actions.py", line 170, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/data/addons/12.0/base_geoengine/geo_model.py", line 103, in fields_view_get
    submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 1085, in postprocess_and_fields
    fields = Model.fields_get(None)
  File "/opt/bitnami/apps/odoo/data/addons/12.0/base_geoengine/geo_model.py", line 26, in fields_get
    allfields=allfields, attributes=attributes)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/models.py", line 2690, in fields_get
    description = field.get_description(self.env)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 746, in get_description
    value = value(env)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190918-py3.7.egg/odoo/fields.py", line 1932, in _description_selection
    return selection(env[self.model_name])
  File "/opt/bitnami/apps/odoo/data/addons/12.0/stock_request/models/stock_request_order.py", line 30, in _get_request_order_states
    return self.__get_request_order_states()
  File "/opt/bitnami/apps/odoo/data/addons/12.0/stock_request/models/stock_request_order.py", line 27, in __get_request_order_states
    return self.env['stock.request']._get_request_states()
  File "/opt/bitnami/apps/odoo/data/addons/12.0/stock_request/models/stock_request.py", line 26, in _get_request_states
    return self.__get_request_states()
  File "/opt/bitnami/apps/odoo/data/addons/12.0/stock_request_submit/models/stock_request.py", line 14, in __get_request_states
    states.index(('draft', _('Draft'))) + 1,
ValueError: ('draft', 'Provisório') is not in list"

**Comment by mileo** [comment]
Hi, i think this is a bug.

By default the selection fields are already translatable, there is no need to translate it at https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_request/models/stock_request.py#L10
and consequently at
https://github.com/OCA/stock-logistics-warehouse/blob/12.0/stock_request_submit/models/stock_request.py#L12

Can test to remove all the translations: _( ) (parentheses with underline). ?

**Comment by augustodinizl** [comment]
Yeahp, worked like a charm, 

TKS

**Comment by mileo** [comment]
Please make a pull request fixing it

**Comment by LoisRForgeFlow** [comment]
@augustodinizl Can you please open the PR against OCA, so everybody benefit from your fix.

Thanks!
