### ISSUE TITLE
[12.0] stock_request_*: ValueError: ('draft', 'Borrador') is not in list

### ISSUE THREAD

**Issue by max3903** [OCA/stock-logistics-warehouse#779]
# Version

12.0

# Steps to reproduce

* Install stock_request_submit in a new DB with a different language than english (I tried with spanish)
* Upgrade the DB

# Result

```
2019-11-29 12:56:07,143 9858 CRITICAL Test odoo.service.server: Failed to initialize database `Test`. 
Traceback (most recent call last):
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 1099, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 924, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 1 more time]
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 884, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/addons/base/models/ir_ui_view.py", line 1090, in postprocess_and_fields
    fields = Model.fields_get(None)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/models.py", line 2690, in fields_get
    description = field.get_description(self.env)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/fields.py", line 754, in get_description
    value = value(env)
  File "/opt/odoo/env/lib/python3.6/site-packages/odoo-12.0-py3.6.egg/odoo/fields.py", line 1940, in _description_selection
    return selection(env[self.model_name])
  File "/opt/odoo/src/stock-logistics-warehouse/stock_request/models/stock_request.py", line 26, in _get_request_states
    return self.__get_request_states()
  File "/opt/odoo/src/stock-logistics-warehouse/stock_request_submit/models/stock_request.py", line 14, in __get_request_states
    states.index(('draft', _('Draft'))) + 1,
ValueError: ('draft', 'Borrador') is not in list
```

# Expected Result

Upgrade completes with no error.

**Comment by LoisRForgeFlow** [comment]
closed via https://github.com/OCA/stock-logistics-warehouse/pull/780
