### ISSUE TITLE
[13.0] in stock_move_location get_putaway_strategy fails

### ISSUE THREAD

**Issue by anderwm** [OCA/stock-logistics-warehouse#850]
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1323, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/extra-addons/stock_move_location/wizard/stock_move_location.py", line 176, in action_move_location
    self._create_moves(picking)
  File "/mnt/extra-addons/stock_move_location/wizard/stock_move_location.py", line 143, in _create_moves
    move = self._create_move(picking, lines)
  File "/mnt/extra-addons/stock_move_location/wizard/stock_move_location.py", line 170, in _create_move
    line.create_move_lines(picking, move)
  File "/mnt/extra-addons/stock_move_location/wizard/stock_move_location_line.py", line 79, in create_move_lines
    values = line._get_move_line_values(picking, move)
  File "/mnt/extra-addons/stock_move_location/wizard/stock_move_location_line.py", line 89, in _get_move_line_values
    and self.destination_location_id.get_putaway_strategy(self.product_id).id
AttributeError: 'stock.location' object has no attribute 'get_putaway_strategy'

**Comment by anderwm** [comment]
I'm not sure exactly how this was working before, but I had to change to this to get what I wanted

        location_dest_id = (
            self.move_location_wizard_id.apply_putaway_strategy
            and self.origin_location_id._get_putaway_strategy(self.product_id).id
            or self.destination_location_id.id
        )

(use origin_location, and now _get_putaway_strategy instead of get_putaway_strategy)
